/**
 * The operator dictionary and its indexes.
 *
 * `operators.json` is generated by `scripts/convert-operators.mjs` and keeps the source
 * field spelling (`code_name`, `sub_job`, `is_recruit`). Renaming the fields on the way
 * in would create a translation layer that has to be maintained for no behavioural gain,
 * and one more place for a divergence to hide. `Operator` is derived from the JSON rather
 * than hand-written, so the type can never drift from the data it describes.
 *
 * ## Six-stars only
 *
 * The file contains 137 entries: rarity {@link RARITY} only, out of 431 in the full
 * operator table. Deck mode — the only feature that drew from every rarity — was dropped,
 * and the drama algorithm never reads past six-stars. The argument in
 * full, including the one all-rarity lookup that went with deck mode, is in the conversion
 * script.
 *
 * The index order below is load-bearing: generation consumes `hash % length` on
 * these arrays, so which operators land in which bucket — and in what order —
 * decides every result. The three indexes have to be built exactly this way:
 *
 *   getOperatorsByJobAndRarity  filters `Object.keys(OPERATORS)`, i.e. dictionary order
 *   OPERATORS_BY_STAR[rarity][job]  that filter, per rarity and job
 *   getStarList(rarity)         flattens the jobs in JOB_ALIAS_MAP order
 *
 * This is why the tests assert both contents *and* key order.
 */

import rawOperators from './operators.json';

/**
 * One dictionary entry, derived from the JSON rather than hand-written so the
 * type cannot drift from the data.
 *
 * Indexed by `keyof` rather than `[string]`: the type TypeScript infers for a
 * JSON module has no string index signature, so `[string]` is an error.
 */
export type Operator = (typeof rawOperators)[keyof typeof rawOperators];

/** The dictionary, keyed by Chinese operator name. Insertion order is meaningful. */
export const OPERATORS: Readonly<Record<string, Operator>> = rawOperators;

/** Job name -> the game's own class id, which is also the source of the English class name. */
export const JOB_ALIAS_MAP = {
	先锋: 'VANGUARD',
	近卫: 'GUARD',
	重装: 'DEFENDER',
	狙击: 'SNIPER',
	术师: 'CASTER',
	医疗: 'MEDIC',
	辅助: 'SUPPORTER',
	特种: 'SPECIALIST'
} as const;

export type OperatorJob = keyof typeof JOB_ALIAS_MAP;

/** The eight jobs, in JOB_ALIAS_MAP's declaration order (the order every loop iterates them in). */
export const JOBS = Object.keys(JOB_ALIAS_MAP) as OperatorJob[];

/**
 * The only rarity that ships.
 *
 * The constant survives as a named value rather than collapsing into a literal `6`
 * because "which rarity are we talking about" is a question the indexes still have to
 * answer, and because the answer is a decision that was made — not a detail.
 */
export const RARITY = 6;

/**
 * Names of every operator with the given rarity and job, in dictionary order.
 *
 * The parameter order is `rarity, job` and is load-bearing: it mirrors how the result is
 * indexed (`OPERATORS_BY_STAR[rarity][job]`), so the call site and the lookup read the
 * same way round.
 */
export function getOperatorsByJobAndRarity(rarity: number, job: OperatorJob): string[] {
	return Object.keys(OPERATORS).filter(
		(name) => OPERATORS[name].job === job && OPERATORS[name].rarity === rarity
	);
}

function buildOperatorsByStar(): Record<string, Record<string, string[]>> {
	const byJob: Record<string, string[]> = {};

	for (const job of JOBS) {
		byJob[job] = getOperatorsByJobAndRarity(RARITY, job);
	}

	// Keyed by rarity rather than flattened, because `OperatorIndex.byStar` is the shape
	// generators read (`byStar['6']['先锋']`) and the shape tests build synthetic copies
	// of. Only the shipped rarity has a key; see `getStarList`.
	return { [String(RARITY)]: byJob };
}

/** `OPERATORS_BY_STAR['6']['先锋']` -> every six-star vanguard, in dictionary order. */
export const OPERATORS_BY_STAR = buildOperatorsByStar();

/**
 * Every operator of one rarity, grouped by job in {@link JOBS} order.
 *
 * Throws for a rarity that does not ship rather than returning `[]`. Those rarities were
 * removed deliberately, and an empty array would report that as "there are no five-stars"
 * — which is a different, wrong statement, and one a caller could act on. A caller asking
 * for five-stars needs to find out that they are gone.
 */
export function getStarList(rarity: number): string[] {
	const byJob = OPERATORS_BY_STAR[String(rarity)];
	if (byJob === undefined) {
		throw new RangeError(`only rarity ${RARITY} ships; asked for ${rarity}`);
	}
	return JOBS.flatMap((job) => byJob[job]);
}

export const OPERATORS_STAR_6_LIST = getStarList(RARITY);

/**
 * The dictionary as generators see it.
 *
 * Threaded through `GeneratorContext` rather than pulled in directly by each
 * generator, for two reasons: a generator cannot then quietly reach for a
 * *different* index than the one its caller built, and a test can drive a
 * generator against a small synthetic dictionary without the real 137 entries.
 */
export interface OperatorIndex {
	/** The eight jobs, in JOB_ALIAS_MAP's declaration order. */
	jobs: readonly OperatorJob[];
	/** `byStar['6']['先锋']` -> six-star vanguards, in dictionary order. */
	byStar: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>>;
	/** Every six-star, jobs in {@link jobs} order. */
	star6: readonly string[];
}

/** The real dictionary, indexed as generators consume it. */
export const OPERATOR_INDEX: OperatorIndex = {
	jobs: JOBS,
	byStar: OPERATORS_BY_STAR,
	star6: OPERATORS_STAR_6_LIST
};
